#define store_x1_30 \
    str x1, [x0], #-8 \
    str x2, [x0], #-8 \
    str x3, [x0], #-8 \
    str x4, [x0], #-8 \
    str x6, [x0], #-8 \
    str x7, [x0], #-8 \
    str x8, [x0], #-8 \
    str x9, [x0], #-8 \
    str x10, [x0], #-8 \
    str x11, [x0], #-8 \
    str x12, [x0], #-8 \
    str x13, [x0], #-8 \
    str x14, [x0], #-8 \
    str x15, [x0], #-8 \
    str x16, [x0], #-8 \
    str x17, [x0], #-8 \
    str x18, [x0], #-8 \
    str x19, [x0], #-8 \
    str x20, [x0], #-8 \
    str x21, [x0], #-8 \
    str x22, [x0], #-8 \
    str x23, [x0], #-8 \
    str x24, [x0], #-8 \
    str x25, [x0], #-8 \
    str x26, [x0], #-8 \
    str x27, [x0], #-8 \
    str x28, [x0], #-8 \
    str x29, [x0], #-8 \
    str x30, [x0], #-8\
    add x0, x0, 240

#define load_x1_30 \
    ldr x1, [x0], #-8 \
    ldr x2, [x0], #-8 \
    ldr x3, [x0], #-8 \
    ldr x4, [x0], #-8 \
    ldr x6, [x0], #-8 \
    ldr x7, [x0], #-8 \
    ldr x8, [x0], #-8 \
    ldr x9, [x0], #-8 \
    ldr x10, [x0], #-8 \
    ldr x11, [x0], #-8 \
    ldr x12, [x0], #-8 \
    ldr x13, [x0], #-8 \
    ldr x14, [x0], #-8 \
    ldr x15, [x0], #-8 \
    ldr x16, [x0], #-8 \
    ldr x17, [x0], #-8 \
    ldr x18, [x0], #-8 \
    ldr x19, [x0], #-8 \
    ldr x20, [x0], #-8 \
    ldr x21, [x0], #-8 \
    ldr x22, [x0], #-8 \
    ldr x23, [x0], #-8 \
    ldr x24, [x0], #-8 \
    ldr x25, [x0], #-8 \
    ldr x26, [x0], #-8 \
    ldr x27, [x0], #-8 \
    ldr x28, [x0], #-8 \
    ldr x29, [x0], #-8 \
    ldr x30, [x0], #-8\
    add x0, x0, 240

